# -*- coding: utf-8 -*-
"""What_can_do_🤗_Transformers.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ca60Y08p5eYOkkM28nY5SWDgURWN0pHH
"""

!pip install datasets evaluate transformers[sentencepiece] gradio

"""## Analyse de Sentiment"""

from transformers import pipeline

classifier = pipeline("sentiment-analysis")
classifier(
    "It is a pleasure for me to participate in this meetup."  
)   # C'est un plaisir pour moi de participer à ce meetup.

import pandas as pd

text = "It is a pleasure for me to participate in this meetup."

output = classifier(text)
pd.DataFrame(output)

"""Ce `pipeline` regroupe trois étapes : le prétraitement, le passage des entrées dans le modèle et le post-traitement.

<img src='https://huggingface.co/datasets/huggingface-course/documentation-images/resolve/main/en/chapter2/full_nlp_pipeline.svg' align='center' width=80%>

On peut faire passer plusieurs phrases:
"""

text = [
        "This course is amazing.",
        "I hate this so much!",
    ]  # « Ce cours est incroyable. »,  « Je déteste tellement ça ! »

outputs = classifier(text)
pd.DataFrame(outputs)

"""## Zero-shot classification

Le `zero-shot-classification` est une tâche qui consiste à classer des textes qui n’ont pas été annotés.
"""

from transformers import pipeline

classifier = pipeline("zero-shot-classification")

classifier(
    "This is a course about the Transformers library",
    # C'est un cours sur la bibliothèque Transformers
    candidate_labels=["education", "politics", "business"],
)

outputs = classifier(
    "This is a course about the Transformers library",
    # C'est un cours sur la bibliothèque Transformers
    candidate_labels=["education", "politics", "business"],
)

pd.DataFrame(outputs)

"""## Generation de Text

L’idée principale ici est que vous fournissez seulement un extrait de texte qui va être complété par du texte généré automatiquement par le modèle.
"""

from transformers import pipeline

generator = pipeline("text-generation")

generator("Linux is the best operating systems", max_length=50) # max_length pour contrôler le nombre caractères générés

"""## Utiliser n'importe quel modèle du Hub dans un pipeline"""

from transformers import pipeline

generator = pipeline("text-generation", model="asi/gpt-fr-cased-base") # pour generer du text en Francais
generator(
    "la vie n'est rien d'autre que le trait d'union du mot peut-être",
    max_length=50
)

"""## Remplacement de mot-masques

L’argument `top_k` permet de contrôler le nombre de possibilités que vous souhaitez afficher. Notez que dans ce cas, le modèle remplace le mot spécial `<mask>`, qui est souvent appelé un `mot masqué`. 
"""

from transformers import pipeline

unmasker = pipeline("fill-mask")
unmasker("This course will teach you all about <mask> models.", top_k=2) # top_k contrôler le nombre de possibilités que vous souhaitez afficher

"""## Reconnaissance d'entités nommées (NER Name Entity Recognition)

La reconnaissance d’entités nommées ou NER (pour Named Entity Recognition) est une tâche où le modèle doit trouver les parties du texte d’entrée qui correspondent à des entités telles que des personnes, des lieux ou des organisations.
"""

# from transformers import pipeline

# ner = pipeline("ner", grouped_entities=True)
# ner(
#     "My name is Astou and I have a great enthusiasm for Data."
# )  # Je m'appelle Astou et j'ai un grand enthousiasme pour les données.

"""## Réponse à des questions

Le pipeline `question-answering` répond à des questions en utilisant des informations données en contexte:
"""

# from transformers import pipeline

# question_answerer = pipeline("question-answering")
# question_answerer(
#     question="Where do I work?",  # Où est-ce que je travaille ?
#     context="My name is Astou and I work at Baamtu Datamation in Dakar",
#     # Je m'appelle Astou et je travaille à Baamtu à Dakar.
# )

# reader = pipeline("question-answering")
# question = "Where do I work?"
# text = "I am Astou and I work at Baamtu in Dakar"
# outputs = reader(question=question, context=text)
# pd.DataFrame([outputs])

"""## Résumé

Le résumé est une tâche de réduction d’un texte en un texte plus court, tout en gardant tous (ou presque tous) les aspects importants référencés dans le texte.
"""

from transformers import pipeline

summarizer = pipeline("summarization")
summarizer(
    """
    
    L'Amérique a changé de façon spectaculaire au cours des dernières années. Non seulement le nombre de 
    diplômés dans les disciplines traditionnelles de l'ingénierie telles que le génie mécanique, civil, 
    l'électricité, la chimie et l'aéronautique a diminué, mais dans la plupart 
    des grandes universités américaines, les programmes d'études d'ingénierie se concentrent désormais sur 
    et encouragent largement l'étude des sciences de l'ingénieur. Par conséquent, il y a 
    de moins en moins d'offres dans les sujets d'ingénierie traitant de l'infrastructure, 
    l'environnement et les questions connexes, et une plus grande concentration sur les sujets de haute 
    technologie, qui soutiennent en grande partie des développements scientifiques de plus en plus 
    complexes. Si cette dernière est importante, elle ne doit pas se faire au détriment
    de l'ingénierie plus traditionnelle.

    Les économies en développement rapide telles que la Chine et l'Inde, ainsi que d'autres 
    pays industrialisés d'Europe et d'Asie, continuent d'encourager et de promouvoir
    l'enseignement de l'ingénierie. La Chine et l'Inde, respectivement, diplôment 
    six et huit fois plus d'ingénieurs traditionnels que les États-Unis. 
    Les autres pays industriels maintiennent au minimum leur production, tandis que l'Amérique 
    souffre d'une baisse de plus en plus importante du nombre de diplômés en ingénierie
    et un manque d'ingénieurs bien formés.

"""
)

"""## Traduction"""

from transformers import pipeline

translator = pipeline("translation", model="Helsinki-NLP/opus-mt-en-fr")
outputs = translator("GalsenAI is a community of AI enthusiasts.")
outputs[0]['translation_text']

"""## Deployer un mini-application de traduction avec Gradio"""

import gradio as gr

def translate_sentence(input_text):
    """Une fonction qui retourne le texte traduit"""
    for value in translator(input_text)[0].values():
        return value

iface = gr.Interface(fn = translate_sentence, inputs = 'text', outputs = 'text',
                     title = "Traduction EN-FR", 
                     description="Un mini google translate avec huggingface")
                     
iface.launch()

